language: python

python:
  - "3.7"

jobs:
  include:
    - stage: "Build Lab 2."
      name: "Run tests for Lab 2"
      python: 3.7
      install:
        - cd ./lab2/
        - pipenv install
      script: pipenv run pytest tests.py || true
    - stage: "Build Lab 4."
      name: "Build Docker images"
      services:
        - docker
      install:
        - cd ./lab4/
      script:
        - docker build -t prometej46297/lab_4:django-travis .
        - docker images
        - if [ "$TRAVIS_PULL_REQUEST" == "false" ]; then echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin; docker push prometej46297/lab_4:django-travis; else echo "PR skip deploy"; fi
    - stage: "Build Lab 5."
      name: "Build and run Docker images, make"
      services:
        - docker
      install:
        - cd ./lab5
      script:
        - make app
        - make tests
branches:
  only:
    - master
