FROM python:3.7-alpine
LABEL author="Prometej"

RUN apk update \
    && apk upgrade \
    && pip install pipenv

WORKDIR /test

COPY test/requirements.txt ./
RUN pipenv install -r requirements.txt

COPY test/ ./

ENTRYPOINT pipenv run pytest test_app.py --url http://app:5000
